export const data=
    {
        id:"1",
        name:"root",
        isFolder:true,
        items:[{
            id:"2",
            name:"src",
            isFolder:true,
            items:[{
                id:"3",
                name:"packages",
                isFolder:true,
                items:[
                    {
                        id:"4",
                        name:"node_modules",
                        isFolder:true,
                        items:[
                            {
                                id:"5",
                                name:"file1.txt",
                                isFolder:false,
                                items:[]
                            },
                            {
                                id:"6",
                                name:"modules",
                                isFolder:true,
                                items:[ {
                                    id:"7",
                                    name:"rename.txt",
                                    isFolder:false,
                                    items:[]
                                },
                                {
                                    id:"9",
                                    name:"modules_file.png",
                                    isFolder:false,
                                    items:[]
                                }]
                            }
                        ]
                    }

                ]
        }]
     }]
    }
